version: 1.0.{build}
image: Visual Studio 2022
configuration: Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: dotnet restore
build:
  verbosity: minimal
after_build:
- cmd: dotnet pack ShouldBeLike\ShouldBeLike.csproj /p:PackageVersion=%APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*/**/*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: N/rBo/LOnSHRgghVjiYUtLQsin1sy7/svuLLuKaoYk+l2kQKmmvZdoUfyeU3jUzU